/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/OXhxWphgbNEQxnUZ/scene.splinecode')
    return (
        <>
            <color attach="background" args={['#5e6063']} />
            <group {...props} dispose={null}>
                <mesh
                    name="Cube"
                    geometry={nodes.Cube.geometry}
                    material={materials['Cube Material']}
                    castShadow
                    receiveShadow
                    position={[99, -36, 340]}
                />
                <mesh
                    name="Sphere 2"
                    geometry={nodes['Sphere 2'].geometry}
                    material={materials['Sphere 2 Material']}
                    castShadow
                    receiveShadow
                    position={[160, 0, 0]}
                />
                <mesh
                    name="Sphere"
                    geometry={nodes.Sphere.geometry}
                    material={materials['Sphere Material']}
                    castShadow
                    receiveShadow
                    position={[-81, -1, 0]}
                />
                <directionalLight
                    name="Directional Light"
                    castShadow
                    intensity={0.7}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={-10000}
                    shadow-camera-far={100000}
                    shadow-camera-left={-500}
                    shadow-camera-right={500}
                    shadow-camera-top={500}
                    shadow-camera-bottom={-500}
                    position={[200, 300, 300]}
                />
                <OrthographicCamera
                    name="1"
                    makeDefault={true}
                    zoom={0.74}
                    far={100000}
                    near={-100000}
                    position={[0, 0, -1000]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                />
                <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
            </group>
        </>
    )
}
